// This file is generated by scripts/sync-generated-app-manifest.mjs.
// Run npm run generated-app-manifest:update after generated app dependency changes.

export type GeneratedAppPackageManifest = {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
};

export const generatedAppPackageManifest: GeneratedAppPackageManifest = {
  dependencies: {
    "@silicajs/auth": "^0.1.3",
    "@silicajs/components": "^0.4.1",
    "@silicajs/core": "^0.9.0",
    "@silicajs/next": "^0.6.0",
    "@silicajs/remark-obsidian": "^0.1.0",
    "@silicajs/search": "^0.3.2",
    "@silicajs/theme-amethyst": "^0.5.1",
    "@silicajs/ui": "^0.2.1",
    "@tailwindcss/postcss": "^4.3.1",
    "better-sqlite3": "^12.11.1",
    jiti: "^2.7.0",
    next: "^16.2.0",
    react: "^19.2.0",
    "react-dom": "^19.2.0",
    tailwindcss: "^4.1.18",
  },
  devDependencies: {
    "@types/better-sqlite3": "^7.6.13",
    "@types/node": "^25.9.3",
    typescript: "^6.0.3",
  },
};
