export {
  assistantModuleTemplate,
  assistantRouteTemplate,
  getSilicaTemplates,
  nextConfigTemplate,
  packageJsonTemplate,
  proxyTemplate,
  themeModuleTemplate,
  tsconfigTemplate,
  type TemplateFile,
} from "./templates.js";
export {
  generatedAppPackageManifest,
  type GeneratedAppPackageManifest,
} from "./generated-app-package-manifest.js";
export {
  getAllSlugs,
  getBacklinks,
  getBreadcrumbs,
  getCacheState,
  getConfig,
  getEntriesForTag,
  getNavigation,
  getPage,
  getPageBySourcePath,
  getPageRuntimeData,
  getProjectRoot,
  getPrerenderSlugs,
  getRenderKey,
  getRelatedTagsForEntries,
  getSilicaRoot,
  getTagSlugs,
  getVaultDatabasePath,
  loadSearchIndex,
  loadRenderEnvironmentHash,
  loadVaultDb,
  normalizeRouteSlug,
  resolveAssetFromDb,
  resolveWikiLinkFromDb,
  type LoadedVaultDb,
} from "./server-data.js";
export { SilicaNextRoutingProvider } from "./routing-provider.js";
