[build]
command = "SILICA_SITE_URL=${URL:-$DEPLOY_PRIME_URL} npx turbo run build --filter=docs"
publish = "docs/.silica/next/.next"

[build.environment]
NODE_VERSION = "22"
SILICA_PROJECT_ROOT = "docs"

[context.deploy-preview.environment]
SILICA_PROJECT_ROOT = "docs"

[context.production.environment]
SILICA_PROJECT_ROOT = "docs"

[[plugins]]
package = "@netlify/plugin-nextjs"
