[build]
command = "SILICA_TIMING_LOGS=1 SILICA_SITE_URL=${URL:-$DEPLOY_PRIME_URL} npx turbo run build --filter=docs"
publish = "docs/.silica/next/.next"

[build.environment]
NODE_VERSION = "22"
SILICA_TIMING_LOGS = "1"

[[plugins]]
package = "@netlify/plugin-nextjs"
