[build]
command = "SILICA_SITE_URL=${URL:-$DEPLOY_PRIME_URL} npm run build --workspace docs"
publish = "docs/.silica/next/.next"

[build.environment]
NODE_VERSION = "22"

[[plugins]]
package = "@netlify/plugin-nextjs"
