export { defineConfig, loadConfig, resolveConfig } from "./config.js";
export { resolvePublicAssetPath } from "./logo.js";
export {
  isMarkdownFile,
  scanContent,
  type ContentAssetFile,
  type ContentMarkdownFile,
  type ContentScan,
} from "./files.js";
export {
  asFilePath,
  asFullSlug,
  asRelativeURL,
  asSimpleSlug,
  createAssetResolutionIndex,
  createWikiLinkResolutionIndex,
  hrefToSlug,
  joinSegments,
  normalizeAssetReference,
  normalizePath,
  normalizeSlug,
  pathToRoot,
  resolveAssetPath,
  resolveRelativeAsset,
  resolveRelative,
  resolveWikiLink,
  simplifySlug,
  slugifyAssetPath,
  slugifyFilePath,
  slugifySegment,
  slugToHref,
  type AssetResolutionEntry,
  type FilePath,
  type AssetResolutionIndex,
  type FullSlug,
  type RelativeURL,
  type SimpleSlug,
  type WikiLinkResolutionIndex,
} from "./path.js";
export {
  formatPropertyLabel,
  formatPropertyValue,
  getMenuLabel,
  getPageProperties,
  type PageProperty,
} from "./pipeline/frontmatter.js";
export {
  analyzeMarkdown,
  generateDescriptionFromContent,
  getDescription,
  getMetaDescription,
  getTitle,
  renderMarkdown,
  renderMarkdownHtml,
} from "./pipeline/index.js";
export {
  getGitDates,
  precompute,
  type PrecomputeOptions,
} from "./precompute.js";
export { tagToHref } from "./tags.js";
export type {
  MarkdownComponents,
  SilicaTheme,
  SilicaCalloutProps,
  SilicaCodeBlockProps,
  SilicaEmbedProps,
  SilicaMermaidProps,
  ThemeBacklink,
  ThemeBreadcrumb,
  ThemeLayoutConfig,
  ThemePage,
  ThemePageProps,
  ThemeProviderComponent,
  ThemeRootLayoutProps,
  ThemeSiteLayoutProps,
} from "./theme.js";
export type {
  AnalyzeResult,
  BrokenLink,
  Graph,
  Manifest,
  ManifestEntry,
  Navigation,
  NavigationEntry,
  PrecomputeResult,
  PrerenderManifest,
  PrerenderSelectorContext,
  RenderContext,
  RenderCacheState,
  RenderResult,
  ResolvedSilicaConfig,
  ResolvedSilicaPrerenderConfig,
  ResolvedSilicaRenderConfig,
  SilicaAuthConfig,
  SilicaConfig,
  SilicaNextConfig,
  SilicaNextConfigOverride,
  SilicaPrerenderConfig,
  SilicaPrerenderSelectionOptions,
  SilicaRenderConfig,
  ThemeConfig,
  TocItem,
} from "./types.js";
