// This file is generated by scripts/sync-scaffold-versions.mjs.
// Run npm run scaffold-versions:update after package version changes.

export const scaffoldDependencyRanges = {
  "@silicajs/cli": "^0.2.0",
  "@silicajs/core": "^0.5.1",
  "@silicajs/next": "^0.3.0",
  "@silicajs/theme-amethyst": "^0.2.3",
} as const;
