// This file is generated by scripts/sync-scaffold-versions.mjs.
// Run npm run scaffold-versions:update after package version changes.

export const scaffoldDependencyRanges = {
  "@silicajs/cli": "^0.1.3",
  "@silicajs/core": "^0.1.1",
  "@silicajs/next": "^0.1.2",
  "@silicajs/theme-amethyst": "^0.1.1",
} as const;
